[package]
name = "uika-codegen"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
uika-ue-flags = { path = "../uika-ue-flags" }
