[package]
name = "uika-ffi"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "FFI types and API table definitions for uika"

[dependencies]
uika-ue-flags = { version = "0.1.0", path = "../uika-ue-flags" }
