[package]
name = "example-game"
version = "0.1.0"
edition.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[features]
wasm-host = ["uika/wasm-host"]

[dependencies]
uika = { path = "../uika", features = ["engine"] }
glam = "0.29"
